Server:
  port: 8080

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Gestiondeformation
    password:
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect